### ISSUE TITLE
scons 出现一下问题

### ISSUE THREAD

**Issue by lionmon** [zlgopen/awtk-linux-fb#51]
使用的是周立功的A9镜像，在Ubuntu下git clone 所有的AWTK源码后，在awtk_config.py中修改了如下：TSLIB_LIB_DIR='/opt/tslib/lib'
TSLIB_INC_DIR='/opt/tslib/include'
TOOLS_PREFIX='/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-'
其他没有修改，然后进行source /opt/poky/1.7/environment-setup-cortexa9hf-vfp-neon-poky-linux-gnueabi 
在然后进行scons出现以下问题
vmuser@ubuntu:~/work/zlgopen$ ls
awtk  awtk-examples  awtk-linux-fb
vmuser@ubuntu:~/work/zlgopen$ scons
Traceback (most recent call last):
  File "/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/lib/python2.7/site.py", line 569, in <module>
    main()
  File "/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/lib/python2.7/site.py", line 551, in main
    known_paths = addusersitepackages(known_paths)
  File "/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/lib/python2.7/site.py", line 278, in addusersitepackages
    user_site = getusersitepackages()
  File "/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/lib/python2.7/site.py", line 253, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/lib/python2.7/site.py", line 242, in getuserbase
    from sysconfig import get_config_var
  File "/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/lib/python2.7/sysconfig.py", line 10, in <module>
    'stdlib': '{base}/'+sys.lib+'/python{py_version_short}',
AttributeError: 'module' object has no attribute 'lib'
vmuser@ubuntu:~/work/zlgopen$ 

这是什么原因导致的，是环境没有配置好吗？这个A9的镜像需要怎么配置环境？

**Comment by xianjimli** [comment]
python2.7不行，要用python3

**Comment by lionmon** [comment]
这个python2.7，是安装交叉编译poky-glibc-x86_64-meta-toolchain-qt5-cortexa9hf-vfp-neon-toolchain-1.7.sh自动生成的，是需要重新安装python3,然后把安装后的文件，复制到那个目录下，直接替换掉python2.7吗？还是需要其他的配置，有没有一个说明参考啊

**Comment by lionmon** [comment]
升级到python3之后，进行scons：
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007efe0441d740 (most recent call first):
Aborted (core dumped)

，请问这个是python3没有配置好的原因吗？在终端输入python  显示的是python3.6版本

**Comment by soyzhc** [comment]
python3.6.6,   scons安装3.1.2 再看看吧，Ubuntu使用16.04
