### ISSUE TITLE
您好，后来解决了scons问题，并能在./build/bin成功生成demoui等文件，但是在执行接下来命令时出现下面问题

### ISSUE THREAD

**Issue by mylk-kwok** [zlgopen/awtk-linux-fb#52]
vmuser@ubuntu:~/awtk-linux-fb$ scons APP=../awtk-examples/HelloWorld-Demo
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: `.' is up to date.
scons: done building targets.
======================== build app ========================
cd ../awtk-examples/HelloWorld-Demo && scons LINUX_FB=true
scons: Reading SConscript files ...
MACH=x86_64 ARCH=('64bit', '') TARGET_ARCH=
TK_ROOT: /home/vmuser/awtk
!!! ERROR: This APP not support LINUX_FB option, scons script will stop!
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/vmuser/awtk-linux-fb/SConstruct", line 94, in build_app
    files = os.listdir(app_bin)
OSError: [Errno 2] No such file or directory: '../awtk-examples/HelloWorld-Demo/bin'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/vmuser/awtk-linux-fb/SConstruct", line 94, in build_app
    files = os.listdir(app_bin)
OSError: [Errno 2] No such file or directory: '../awtk-examples/HelloWorld-Demo/bin'
vmuser@ubuntu:~/awtk-linux-fb$

**Comment by mylk-kwok** [comment]
awtk_config.py文件我修改了这里
#for prebuild tslib
#TSLIB_LIB_DIR='/opt/28x/tslib/lib'
#TSLIB_INC_DIR='/opt/28x/tslib/include'
#TOOLS_PREFIX='/opt/28x/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/bin/arm-linux-'
#TOOLS_PREFIX='/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-'

#for pc build
TOOLS_PREFIX='/opt/gcc-linaro-arm-linux-gnueabihf-4.9-2014.09_linux/bin/arm-linux-gnueabihf-'
#TOOLS_PREFIX=''
TSLIB_LIB_DIR=''
TARGET_ARCH = platform.architecture();

**Comment by xianjimli** [comment]
试试v2: https://github.com/zlgopen/awtk-examples.v2

**Comment by lionmon** [comment]
你好，你的scons怎么解决的，能否发一下解决办法，谢谢啦

**Comment by mylk-kwok** [comment]
@lionmon 我重新安装的Ubuntu系统，并配置了开发环境
