### ISSUE TITLE
如何在imx6的下移植

### ISSUE THREAD

**Issue by likun117** [zlgopen/awtk-linux-fb#55]
修改好awtk_config.py后，使用imx的编译，
**source /opt/imx6/environment-setup-cortexa7hf-vfp-neon-poky-linux-gnueabi** 
Traceback (most recent call last):
  File "/opt/imx6/sysroots/x86_64-pokysdk-linux/usr/lib/python2.7/site.py", line 553, in <module>
    main()
  File "/opt/imx6/sysroots/x86_64-pokysdk-linux/usr/lib/python2.7/site.py", line 535, in main
    known_paths = addusersitepackages(known_paths)
  File "/opt/imx6/sysroots/x86_64-pokysdk-linux/usr/lib/python2.7/site.py", line 266, in addusersitepackages
    user_site = getusersitepackages()
  File "/opt/imx6/sysroots/x86_64-pokysdk-linux/usr/lib/python2.7/site.py", line 241, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/opt/imx6/sysroots/x86_64-pokysdk-linux/usr/lib/python2.7/site.py", line 230, in getuserbase
    from sysconfig import get_config_var
  File "/opt/imx6/sysroots/x86_64-pokysdk-linux/usr/lib/python2.7/sysconfig.py", line 10, in <module>
    'stdlib': '{base}/'+sys.lib+'/python{py_version_short}',
AttributeError: 'module' object has no attribute 'lib'

**不导入环境变量**
 src/app_main.c
In file included from /home/aven/share/03public/awtk-v1.5+rc.5/awtk/src/tkc/value.h:22:0,
                 from /home/aven/share/03public/awtk-v1.5+rc.5/awtk/src/tkc/event.h:25,
                 from /home/aven/share/03public/awtk-v1.5+rc.5/awtk/src/tkc/qaction.h:25,
                 from /home/aven/share/03public/awtk-v1.5+rc.5/awtk/src/tkc/action_queue.h:25,
                 from /home/aven/share/03public/awtk-v1.5+rc.5/awtk/src/awtk_tkc.h:25,
                 from /home/aven/share/03public/awtk-v1.5+rc.5/awtk/src/awtk.h:25,
                 from src/app_main.c:4:
/home/aven/share/03public/awtk-v1.5+rc.5/awtk/src/tkc/types_def.h:25:18: fatal error: math.h: No such file or directory

怎么才算是正确的操作？

**Comment by xianjimli** [comment]
* 最好用 AWTK 1.6。
* 需要使用python 3。
* 如果从ZLG拿的芯片，找FAE，他们有移植好的版本。

**Comment by soyzhc** [comment]
建议用python3 和scons 3.x 以上版本
缺少math.h一般是工具链路径没有设置对

**Comment by likun117** [comment]
yocto编译的交叉编译工具在这个上面使用有点问题，我换了个linaro交叉编译工具
