### ISSUE TITLE
移植到linux系统下，调用update_res.py脚本报错。

### ISSUE THREAD

**Issue by Ttwus** [zlgopen/awtk-linux-fb#76]
移植到linux系统下，调用update_res.py脚本报错。已调整过“AWTK_ROOT”，依旧提示No module named update_res_app。
如何在移植后的环境下调用update_res.py脚本生成资源？

**Comment by xianjimli** [comment]
把操作步骤和相应的log贴上来吧。

**Comment by Ttwus** [comment]
移植的步骤是按照github上的操作的，其中不同点就是把awtk文件名改成了awtk-linux。其他的就是对应的修改了。
update_res.py脚本用的的是demo默认的没有修改。
log：
AWTK_ROOT: /home/zyb/AK37E_SDK_V1.02/application/gui/awtk
AWTK_SCRIPTS_ROOT: /home/zyb/AK37E_SDK_V1.02/application/gui/awtk/scripts
Traceback (most recent call last):
  File "./scripts/update_res.py", line 41, in <module>
    update_res(ARGUMENTS, is_new_usage)
  File "./scripts/update_res.py", line 27, in update_res
    import update_res_app as updater
ImportError: No module named update_res_app

**Comment by xianjimli** [comment]
不要改名

**Comment by Ttwus** [comment]
如果改名了，是不是在demo的project.json文件中应修改"awtkRoot"的位置？

**Comment by Ttwus** [comment]
"awtkRoot": "${DesignerPath}/SDK/awtk" 改为

**Comment by Ttwus** [comment]
> "awtkRoot": "${DesignerPath}/SDK/awtk-linux"

**Comment by xianjimli** [comment]
最好不要改，先跑起来了再研究。

**Comment by fatalfeel** [comment]
Here is the process of porting to embeeded linux on arm64 & demo for your reference
AWTK is easy to use. Thanks to Master Lee for sharing more than ten years of experience
https://fatalfeel.blogspot.com/2013/12/awtk-framebuffer-gui.html
https://www.mediafire.com/file/6574qtf1hw92vey/awtk.mp4
